[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "scdv"
version = "0.2.8"
description = "StarCitizen Data Viewer"
authors = [ "Ventorvar <ventorvar@gmail.com>",]

[tool.briefcase]
project_name = "SCDV"
bundle = "scdatatools.scdv"
version = "0.2.8"
url = "https://gitlab.com/scmodding/tools/scdv"
license = "MIT license"
author = "Ventorvar"
author_email = "ventorvar@gmail.com"

[tool.poetry.dependencies]
python = ">=3.8"
QtPy = "^1.9.0"
PySide2 = "^5.15.2"
Pillow = "^8.0.1"
qtconsole = "^5.0.1"
scdatatools = "^0.1.7"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
briefcase = "^0.3.3"

[tool.briefcase.app.scdv]
formal_name = "SCDV"
description = "Star Citizen Data Viewer"
icon = "scdv/resources/scdv"
installer_icon = "scdv/resources/scdv"
sources = [ "scdv",]
requires = [ "-r", "dist/requirements.txt",]

[tool.briefcase.app.scdv.macOS]
requires = []

[tool.briefcase.app.scdv.linux]
requires = []
system_requires = []

[tool.briefcase.app.scdv.windows]
requires = []

[tool.briefcase.app.scdv.iOS]
requires = []

[tool.briefcase.app.scdv.android]
requires = []
